### ISSUE TITLE
Inject a verse or verses into org-mode buffer

### ISSUE THREAD

**Issue by oatmealm** [alhassy/holy-books#13]
I'm assuming I'm missing the point, but is there a way to invoke on of the available functions to inject the text in Arabic into the. Offer I'm currently working in? I was a ale to see the translated text returned, but can't see how I get the original text in Arabic. 

Thanks for a great idea!

**Comment by alhassy** [comment]
As of right now, no Arabic is being pulled in. However, this is a great idea, so I've implemented it as `holy-books-insert-quran`  ---thanks for the idea!

Now just `M-x holy-books-insert-quran` or `C-c h`  if you use `use-package`:

    (use-package holy-books
       :bind ("C-c h" . holy-books-insert-quran))

All the best!

**Comment by oatmealm** [comment]
Wonderful! Will look shortly.

BTW are you aware of project Sefaria? Not sure if they have an API available though. 

https://www.sefaria.org/?lang=bi
