### ISSUE TITLE
Request for Discussion Section

### ISSUE THREAD

**Issue by hwpplayer1** [alhassy/holy-books#2]
Could you please write a Code of Conduct, Contributing, Pull Request Templates, Issue Templates and for all to discuss could you please open Discussion Section for the Internet ? 

Thanks and Happy Emacs Hacking!

**Comment by alhassy** [comment]
Hey @hwpplayer1, I like your spirit!

I've opened a Discussions section.

Regarding PR templates, I'd like it if people contributed to the `holy-books.org` file and tangled the resulting Lisp; but I'm okay with people altering the Lisp file directly and I'll backpropagate it to the literate Org file. (Ideally, the changes would stay in alignment with the Melpa package requirements ---which are mentioned in the Org file.)

Regarding the other ideas you have, I unfortunately don't have too much time to set that up ---this project was done quickly in my spare time over the past week. However, you're welcome to set these things up and I'll merge them in :-)

All the best!

**Comment by hwpplayer1** [comment]
@alhassy Thanks for your help and your understanding and kind words and I started taking responsibility It will take time to think of that But I will be careful to make for the good

https://github.com/alhassy/holy-books/discussions/5

**Comment by alhassy** [comment]
I look forward to working with you @hwpplayer1  :-)
